<?php
	$helper = Mage::Helper('payson');
	$code = $this->getMethodCode();
?>
<fieldset class="form-list">
	<label for="p_method_<?php echo($code); ?>" style="float: none"><img src="<?php echo(Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)); ?>frontend/base/default/Payson/Payson/payson_faktura.png" alt="Payson" style="margin: 10px 0; display: block" /></label>
	<p id="payment_form_<?php echo($code); ?>" style="display: none">
        <?php 
            echo($helper->__('You will be redirected to Payson\'s website.')); 
            echo '<br /><br />';
            echo($helper->__('If you choose to pay by Paysoninvoice so there is a fee. Payment terms are 10 days and the invoice will be sent separately by email to the email address you specify. To pay by Paysoninvoice You must be 18 years old and be registered in Sweden as well as authorized in the credit assessment carried out at purchase.')); 
        ?>
        </p>
</fieldset>

